### ISSUE TITLE
button-lua PKGBUILD missing xxd dependency

### ISSUE THREAD

**Issue by mihails-strasuns** [jasonwhite/brilliant-build-lua#1]
https://aur.archlinux.org/packages/button-lua is using xxd binary during the build but doesn't mention it in build dependencies. 

xxd is normally provided as part of vim package but I have also created a stand-alone AUR one: https://aur.archlinux.org/packages/xxd-vim

**Comment by jasonwhite** [comment]
Thanks. It should be fixed now. I added the dependency on `xxd` to the `PKGBUILD`. It should let you choose between the different providers of `xxd` (including `xxd-vim`).

Eventually, I think I'll just write a simple version of `xxd` to remove this dependency and so it can also build on Windows without Cygwin.

**Comment by mihails-strasuns** [comment]
All good, thanks.
