### ISSUE TITLE
New input that would match `glob` is ignored

### ISSUE THREAD

**Issue by mihails-strasuns** [jasonwhite/brilliant-build-lua#2]
This may be a fundamental problem of how button-lua is designed to work but I am curious to hear your opinion.

Consider typical recursive build with `BUILD.lua` defining simple D binary:

```
local app   = d.binary {
    name        = "app",
    srcs          = glob { "source/*.d" }
}
```

Works just fine on first run. Now you add more D source files to `source` folder and run `button build` again and nothing happens at all. Which makes sense because button knows nothing of `glob` mask, it only tracks dependencies based on json file which will contain exact file list lua script has found on first run. And considering neither lua script nor any of original sources has been changed, it deduces that everything is up to date.

**Comment by jasonwhite** [comment]
I've known about this for a while. This isn't a fundamental problem. It can be solved, I just haven't gotten around to it yet.

This is all that needs to be done for this to work properly:
1. Add support for directory resources in `button`.
   
   This involves:
   - Hashing the sorted list of files in a directory to keep track of changes to the directory.
   - Making sure we handle the case where a path changes from a directory to a file and vice versa.
2. Make `glob` in `button-lua` report every directory it looks at as an implicit dependency.

**Comment by mihails-strasuns** [comment]
Thanks! I tried to test it quickly by modifying `tests/d/build.lua` snippet to use `glob` as source - is the expected change that the folder path itself should be listed in `"inputs"`? I don't see it in generated json.

**Comment by jasonwhite** [comment]
There was another required change to `button` itself that I just merged in: https://github.com/jasonwhite/button/pull/14

The dependent directories are now published by `glob` as implicit dependencies to `button` which then takes care of tracking changes to them. There is no need to make these dependencies explicit by adding them to the generated JSON build description.

Unfortunately, I also accidentally used C++11 when implementing this. So I either need to make GCC use C++11 or remove the C++11-specific bits. :tired_face:

**Comment by mihails-strasuns-sociomantic** [comment]
Damn, I do need to get deep into sources at some point to stop asking stupid questions. With both PRs adding/removing files indeed seems to work!

Talking about C++ - was there any reason why that part was not written in D?

**Comment by mihails-strasuns** [comment]
Damn, I do need to get deep into sources at some point to stop asking stupid questions. With both PRs adding/removing files indeed seems to work!

Talking about C++ - was there any reason why that part was not written in D?

**Comment by jasonwhite** [comment]
The main reason I chose C++ over D for this project is because of Lua. [LuaD][] is still using Lua 5.1. I wanted to support Lua 5.2 and 5.3. [DerelictLua][] is just bindings to a dynamically loaded Lua library and I wanted the option to statically link with Lua.

I also figured that there would be much more Lua code than C++ code, so it wouldn't really matter.

[LuaD]: https://github.com/JakobOvrum/LuaD
[DerelictLua]: https://github.com/DerelictOrg/DerelictLua
